### ISSUE TITLE
Vercel 部署中报错

### ISSUE THREAD

**Issue by thedavidweng** [izuolan/notionic#19]
报错咯
<img width="1246" alt="Screenshot 2023-03-18 at 10 27 06" src="https://user-images.githubusercontent.com/95214375/226123089-42795b8a-1c80-41e7-b89d-311c9887720e.png">

```shell

[10:23:07.059] Running build in Cleveland, USA (East) – cle1
[10:23:07.111] Cloning github.com/thedavidweng/notionic (Branch: main, Commit: 4b3327f)
[10:23:07.360] Previous build cache not available
[10:23:07.533] Cloning completed: 421.587ms
[10:23:07.635] Running "vercel build"
[10:23:08.093] Vercel CLI 28.17.0
[10:23:08.345] Installing dependencies...
[10:23:08.651] yarn install v1.22.17
[10:23:08.731] [1/4] Resolving packages...
[10:23:08.901] [2/4] Fetching packages...
[10:23:21.300] [3/4] Linking dependencies...
[10:23:21.303] warning "react-notion-x > react-image@4.0.3" has unmet peer dependency "@babel/runtime@>=7".
[10:23:21.304] warning "react-notion-x > react-lazy-images@1.1.0" has incorrect peer dependency "react@^15 || ^16".
[10:23:21.304] warning "react-notion-x > react-lazy-images@1.1.0" has incorrect peer dependency "react-dom@^15 || ^16".
[10:23:21.305] warning "react-notion-x > react-pdf > file-loader@6.2.0" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
[10:23:21.306] warning "eslint-config-next > @typescript-eslint/parser > @typescript-eslint/typescript-estree > tsutils@3.21.0" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
[10:23:21.307] warning " > next-sitemap@3.1.29" has unmet peer dependency "@next/env@*".
[10:23:30.429] [4/4] Building fresh packages...
[10:23:31.548] $ husky install
[10:23:31.619] husky - Git hooks installed
[10:23:31.624] Done in 22.98s.
[10:23:31.653] Detected Next.js version: 12.1.0
[10:23:31.655] Running "yarn run build"
[10:23:31.833] yarn run v1.22.17
[10:23:31.878] $ next build
[10:23:32.529] Attention: Next.js now collects completely anonymous telemetry regarding usage.
[10:23:32.529] This information is used to shape Next.js' roadmap and prioritize features.
[10:23:32.530] You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
[10:23:32.530] https://nextjs.org/telemetry
[10:23:32.530] 
[10:23:32.548] Browserslist: caniuse-lite is outdated. Please run:
[10:23:32.548]   npx browserslist@latest --update-db
[10:23:32.548]   Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
[10:23:32.598] info  - Checking validity of types...
[10:23:33.954] Browserslist: caniuse-lite is outdated. Please run:
[10:23:33.954]   npx browserslist@latest --update-db
[10:23:33.954]   Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
[10:23:36.358] info  - Creating an optimized production build...
[10:23:36.649] Browserslist: caniuse-lite is outdated. Please run:
[10:23:36.649] npx browserslist@latest --update-db
[10:23:36.650] 
[10:23:36.650] Why you should do it regularly:
[10:23:36.650] https://github.com/browserslist/browserslist#browsers-data-updating
[10:23:37.581] Browserslist: caniuse-lite is outdated. Please run:
[10:23:37.582]   npx browserslist@latest --update-db
[10:23:37.582]   Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
[10:23:52.018] info  - Compiled successfully
[10:23:52.019] info  - Collecting page data...
[10:23:54.093] failed to create preview image https://www.notion.so/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2F7f305d66-3357-4b12-8d18-9bd4678d230c%2Fandroid-chrome-512x512.png?table=block&id=5b0559f1-9bd0-4227-b643-ae30fbd75080&cache=v2 Response code 400 (Bad Request)
[10:23:57.243] failed to create preview image https://www.notion.so/image/%2F%2Fi1.hdslb.com%2Fbfs%2Farchive%2F57735d112ad164a8dc02bde08621e6c5202d2e7d.jpg%40100w_100h_1c.png%4057w_57h_1c.png?table=block&id=087575e7-714e-4638-aa31-b90bccf30d01&cache=v2 Response code 400 (Bad Request)
[10:23:58.467] failed to create preview image https://www.notion.so/image/%2F%2Fi0.hdslb.com%2Fbfs%2Farchive%2Fa044e5d87652ab34ad4f9e44b86660d2059dd803.jpg%40100w_100h_1c.png%4057w_57h_1c.png?table=block&id=0fbd978c-b469-4706-909a-77c16b02bee2&cache=v2 Response code 400 (Bad Request)
[10:23:58.901] failed to create preview image https://www.notion.so/image/%2F%2Fi2.hdslb.com%2Fbfs%2Farchive%2F1fdb2c241496707da1d158f6131828ee9d77cf45.jpg%40100w_100h_1c.png%4057w_57h_1c.png?table=block&id=ccb44b9b-9cf0-4aac-89b9-b52419604b99&cache=v2 Response code 400 (Bad Request)
[10:24:00.555] failed to create preview image https://www.notion.so/image/https%3A%2F%2Fwww.jimmytian.com%2Ffavicon.ico?table=block&id=c86b1841-5878-4d53-9e26-2309de2e73ca&cache=v2 Response code 404 (Not Found)
[10:24:00.875] failed to create preview image https://www.notion.so/image/https%3A%2F%2Fwww.notion.so%2Fimage%2Fhttps%253A%252F%252Fs3-us-west-2.amazonaws.com%252Fsecure.notion-static.com%252F8d22dd96-87d2-44a9-b254-0de68bb97812%252F6B24639E95BA41848A56C932DA33497B.jpg%3Ftable%3Dblock%26id%3D7ee1ddcf-b3a9-4713-b614-bcb47ddd97a2%26cache%3Dv2?table=block&id=2374cc02-9726-42fa-898d-53b2db2fb089&cache=v2 Response code 404 (Not Found)
[10:24:17.165] info  - Generating static pages (0/108)
[10:24:17.332] 
[10:24:17.332] Error occurred prerendering page "/contact". Read more: https://nextjs.org/docs/messages/prerender-error
[10:24:17.332] TypeError: Cannot read properties of undefined (reading 'slice')
[10:24:17.333]     at contact_Contact (/vercel/path0/.next/server/pages/contact.js:195:78)
[10:24:17.333]     at d (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:33:498)
[10:24:17.333]     at bb (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:16)
[10:24:17.333]     at b.render (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:42:43)
[10:24:17.333]     at b.read (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)
[10:24:17.333]     at exports.renderToString (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:52:138)
[10:24:17.333]     at Object.renderPage (/vercel/path0/node_modules/next/dist/server/render.js:751:45)
[10:24:17.333]     at Object.defaultGetInitialProps (/vercel/path0/node_modules/next/dist/server/render.js:389:51)
[10:24:17.333]     at Document.getInitialProps (/vercel/path0/.next/server/chunks/859.js:503:20)
[10:24:17.333]     at MyDocument.getInitialProps (/vercel/path0/.next/server/pages/_document.js:25:90)
[10:24:20.161] failed to create preview image https://www.notion.so/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2F7f305d66-3357-4b12-8d18-9bd4678d230c%2Fandroid-chrome-512x512.png?table=block&id=5b0559f1-9bd0-4227-b643-ae30fbd75080&cache=v2 Response code 400 (Bad Request)
[10:24:20.405] failed to create preview image https://www.notion.so/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2F7f305d66-3357-4b12-8d18-9bd4678d230c%2Fandroid-chrome-512x512.png?table=block&id=5b0559f1-9bd0-4227-b643-ae30fbd75080&cache=v2 Response code 400 (Bad Request)
[10:24:21.951] failed to create preview image https://www.notion.so/image/%2F%2Fi1.hdslb.com%2Fbfs%2Farchive%2F57735d112ad164a8dc02bde08621e6c5202d2e7d.jpg%40100w_100h_1c.png%4057w_57h_1c.png?table=block&id=087575e7-714e-4638-aa31-b90bccf30d01&cache=v2 Response code 400 (Bad Request)
[10:24:24.771] failed to create preview image https://www.notion.so/image/%2F%2Fi2.hdslb.com%2Fbfs%2Farchive%2F1fdb2c241496707da1d158f6131828ee9d77cf45.jpg%40100w_100h_1c.png%4057w_57h_1c.png?table=block&id=ccb44b9b-9cf0-4aac-89b9-b52419604b99&cache=v2 Response code 400 (Bad Request)
[10:24:26.038] failed to create preview image https://www.notion.so/image/https%3A%2F%2Fwww.jimmytian.com%2Ffavicon.ico?table=block&id=c86b1841-5878-4d53-9e26-2309de2e73ca&cache=v2 Response code 404 (Not Found)
[10:24:29.968] info  - Generating static pages (27/108)
[10:24:43.986] info  - Generating static pages (54/108)
[10:24:46.928] failed to create preview image https://www.notion.so/image/%2F%2Fi1.hdslb.com%2Fbfs%2Farchive%2F57735d112ad164a8dc02bde08621e6c5202d2e7d.jpg%40100w_100h_1c.png%4057w_57h_1c.png?table=block&id=087575e7-714e-4638-aa31-b90bccf30d01&cache=v2 Response code 400 (Bad Request)
[10:24:48.226] failed to create preview image https://www.notion.so/image/%2F%2Fi2.hdslb.com%2Fbfs%2Farchive%2F1fdb2c241496707da1d158f6131828ee9d77cf45.jpg%40100w_100h_1c.png%4057w_57h_1c.png?table=block&id=ccb44b9b-9cf0-4aac-89b9-b52419604b99&cache=v2 Response code 400 (Bad Request)
[10:24:50.013] failed to create preview image https://www.notion.so/image/https%3A%2F%2Fwww.jimmytian.com%2Ffavicon.ico?table=block&id=c86b1841-5878-4d53-9e26-2309de2e73ca&cache=v2 Response code 404 (Not Found)
[10:24:51.367] failed to create preview image https://www.notion.so/image/https%3A%2F%2Fwww.notion.so%2Fimage%2Fhttps%253A%252F%252Fs3-us-west-2.amazonaws.com%252Fsecure.notion-static.com%252F8d22dd96-87d2-44a9-b254-0de68bb97812%252F6B24639E95BA41848A56C932DA33497B.jpg%3Ftable%3Dblock%26id%3D7ee1ddcf-b3a9-4713-b614-bcb47ddd97a2%26cache%3Dv2?table=block&id=2374cc02-9726-42fa-898d-53b2db2fb089&cache=v2 Response code 404 (Not Found)
[10:24:58.671] info  - Generating static pages (81/108)
[10:25:02.219] 
[10:25:02.219] Error occurred prerendering page "/en/contact". Read more: https://nextjs.org/docs/messages/prerender-error
[10:25:02.220] TypeError: Cannot read properties of undefined (reading 'slice')
[10:25:02.220]     at contact_Contact (/vercel/path0/.next/server/pages/contact.js:195:78)
[10:25:02.220]     at d (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:33:498)
[10:25:02.220]     at bb (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:16)
[10:25:02.220]     at b.render (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:42:43)
[10:25:02.220]     at b.read (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)
[10:25:02.221]     at exports.renderToString (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:52:138)
[10:25:02.221]     at Object.renderPage (/vercel/path0/node_modules/next/dist/server/render.js:751:45)
[10:25:02.221]     at Object.defaultGetInitialProps (/vercel/path0/node_modules/next/dist/server/render.js:389:51)
[10:25:02.221]     at Document.getInitialProps (/vercel/path0/.next/server/chunks/859.js:503:20)
[10:25:02.221]     at MyDocument.getInitialProps (/vercel/path0/.next/server/pages/_document.js:25:90)
[10:25:02.222] 
[10:25:02.222] Error occurred prerendering page "/zh/contact". Read more: https://nextjs.org/docs/messages/prerender-error
[10:25:02.222] TypeError: Cannot read properties of undefined (reading 'slice')
[10:25:02.222]     at contact_Contact (/vercel/path0/.next/server/pages/contact.js:195:78)
[10:25:02.222]     at d (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:33:498)
[10:25:02.222]     at bb (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:16)
[10:25:02.222]     at b.render (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:42:43)
[10:25:02.222]     at b.read (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)
[10:25:02.222]     at exports.renderToString (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:52:138)
[10:25:02.222]     at Object.renderPage (/vercel/path0/node_modules/next/dist/server/render.js:751:45)
[10:25:02.222]     at Object.defaultGetInitialProps (/vercel/path0/node_modules/next/dist/server/render.js:389:51)
[10:25:02.222]     at Document.getInitialProps (/vercel/path0/.next/server/chunks/859.js:503:20)
[10:25:02.222]     at MyDocument.getInitialProps (/vercel/path0/.next/server/pages/_document.js:25:90)
[10:25:04.036] TypeError: Cannot read properties of undefined (reading 'id')
[10:25:04.037]     at getStaticProps (/vercel/path0/.next/server/pages/index.js:212:100)
[10:25:04.037]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[10:25:04.037]     at async renderToHTML (/vercel/path0/node_modules/next/dist/server/render.js:465:20)
[10:25:04.037]     at async /vercel/path0/node_modules/next/dist/export/worker.js:269:36
[10:25:04.037]     at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:75:20)
[10:25:04.037] 
[10:25:04.037] Error occurred prerendering page "/en". Read more: https://nextjs.org/docs/messages/prerender-error
[10:25:04.037] Error: Error serializing `.blockMap` returned from `getStaticProps` in "/".
[10:25:04.038] Reason: `undefined` cannot be serialized as JSON. Please use `null` or omit this value.
[10:25:04.038]     at isSerializable (/vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:30:19)
[10:25:04.038]     at /vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:37:66
[10:25:04.038]     at Array.every (<anonymous>)
[10:25:04.038]     at isSerializable (/vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:34:39)
[10:25:04.038]     at Object.isSerializableProps (/vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:57:12)
[10:25:04.038]     at renderToHTML (/vercel/path0/node_modules/next/dist/server/render.js:521:93)
[10:25:04.038]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[10:25:04.039]     at async /vercel/path0/node_modules/next/dist/export/worker.js:269:36
[10:25:04.039]     at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:75:20)
[10:25:04.242] TypeError: Cannot read properties of undefined (reading 'id')
[10:25:04.242]     at getStaticProps (/vercel/path0/.next/server/pages/index.js:212:100)
[10:25:04.242]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[10:25:04.242]     at async renderToHTML (/vercel/path0/node_modules/next/dist/server/render.js:465:20)
[10:25:04.242]     at async /vercel/path0/node_modules/next/dist/export/worker.js:269:36
[10:25:04.242]     at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:75:20)
[10:25:04.242] 
[10:25:04.242] Error occurred prerendering page "/zh". Read more: https://nextjs.org/docs/messages/prerender-error
[10:25:04.242] Error: Error serializing `.blockMap` returned from `getStaticProps` in "/".
[10:25:04.242] Reason: `undefined` cannot be serialized as JSON. Please use `null` or omit this value.
[10:25:04.242]     at isSerializable (/vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:30:19)
[10:25:04.243]     at /vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:37:66
[10:25:04.243]     at Array.every (<anonymous>)
[10:25:04.243]     at isSerializable (/vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:34:39)
[10:25:04.243]     at Object.isSerializableProps (/vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:57:12)
[10:25:04.243]     at renderToHTML (/vercel/path0/node_modules/next/dist/server/render.js:521:93)
[10:25:04.243]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[10:25:04.243]     at async /vercel/path0/node_modules/next/dist/export/worker.js:269:36
[10:25:04.243]     at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:75:20)
[10:25:04.300] TypeError: Cannot read properties of undefined (reading 'id')
[10:25:04.300]     at getStaticProps (/vercel/path0/.next/server/pages/newsletter.js:239:100)
[10:25:04.300]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[10:25:04.300]     at async renderToHTML (/vercel/path0/node_modules/next/dist/server/render.js:465:20)
[10:25:04.301]     at async /vercel/path0/node_modules/next/dist/export/worker.js:269:36
[10:25:04.301]     at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:75:20)
[10:25:04.301] 
[10:25:04.301] Error occurred prerendering page "/en/newsletter". Read more: https://nextjs.org/docs/messages/prerender-error
[10:25:04.301] Error: Error serializing `.blockMap` returned from `getStaticProps` in "/newsletter".
[10:25:04.301] Reason: `undefined` cannot be serialized as JSON. Please use `null` or omit this value.
[10:25:04.301]     at isSerializable (/vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:30:19)
[10:25:04.301]     at /vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:37:66
[10:25:04.301]     at Array.every (<anonymous>)
[10:25:04.301]     at isSerializable (/vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:34:39)
[10:25:04.301]     at Object.isSerializableProps (/vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:57:12)
[10:25:04.301]     at renderToHTML (/vercel/path0/node_modules/next/dist/server/render.js:521:93)
[10:25:04.301]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[10:25:04.301]     at async /vercel/path0/node_modules/next/dist/export/worker.js:269:36
[10:25:04.301]     at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:75:20)
[10:25:04.624] [INFO] Hide Craft Table Header:  1 1
[10:25:04.625] [INFO] Hide Craft Table Header:  4 4
[10:25:04.625] [INFO] Hide Craft Table Header:  4 4
[10:25:04.625] [INFO] Hide Craft Table Header:  4 4
[10:25:04.802] [INFO] Hide Craft Table Header:  1 1
[10:25:04.802] [INFO] Hide Craft Table Header:  4 4
[10:25:04.802] [INFO] Hide Craft Table Header:  4 4
[10:25:04.802] [INFO] Hide Craft Table Header:  4 4
[10:25:04.934] TypeError: Cannot read properties of undefined (reading 'id')
[10:25:04.934]     at getStaticProps (/vercel/path0/.next/server/pages/newsletter.js:239:100)
[10:25:04.934]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[10:25:04.934]     at async renderToHTML (/vercel/path0/node_modules/next/dist/server/render.js:465:20)
[10:25:04.934]     at async /vercel/path0/node_modules/next/dist/export/worker.js:269:36
[10:25:04.935]     at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:75:20)
[10:25:04.935] 
[10:25:04.935] Error occurred prerendering page "/zh/newsletter". Read more: https://nextjs.org/docs/messages/prerender-error
[10:25:04.935] Error: Error serializing `.blockMap` returned from `getStaticProps` in "/newsletter".
[10:25:04.935] Reason: `undefined` cannot be serialized as JSON. Please use `null` or omit this value.
[10:25:04.935]     at isSerializable (/vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:30:19)
[10:25:04.935]     at /vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:37:66
[10:25:04.935]     at Array.every (<anonymous>)
[10:25:04.935]     at isSerializable (/vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:34:39)
[10:25:04.935]     at Object.isSerializableProps (/vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:57:12)
[10:25:04.935]     at renderToHTML (/vercel/path0/node_modules/next/dist/server/render.js:521:93)
[10:25:04.935]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[10:25:04.935]     at async /vercel/path0/node_modules/next/dist/export/worker.js:269:36
[10:25:04.936]     at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:75:20)
[10:25:05.072] TypeError: Cannot read properties of undefined (reading 'id')
[10:25:05.072]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[10:25:05.073]     at async renderToHTML (/vercel/path0/node_modules/next/dist/server/render.js:465:20)
[10:25:05.073]     at async /vercel/path0/node_modules/next/dist/export/worker.js:269:36
[10:25:05.073]     at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:75:20)
[10:25:05.073] 
[10:25:05.073] Error occurred prerendering page "/en/notes". Read more: https://nextjs.org/docs/messages/prerender-error
[10:25:05.073] Error: Error serializing `.blockMap` returned from `getStaticProps` in "/notes".
[10:25:05.073] Reason: `undefined` cannot be serialized as JSON. Please use `null` or omit this value.
[10:25:05.073]     at isSerializable (/vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:30:19)
[10:25:05.073]     at /vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:37:66
[10:25:05.073]     at Array.every (<anonymous>)
[10:25:05.073]     at isSerializable (/vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:34:39)
[10:25:05.073]     at Object.isSerializableProps (/vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:57:12)
[10:25:05.073]     at renderToHTML (/vercel/path0/node_modules/next/dist/server/render.js:521:93)
[10:25:05.073]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[10:25:05.073]     at async /vercel/path0/node_modules/next/dist/export/worker.js:269:36
[10:25:05.073]     at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:75:20)
[10:25:05.175] TypeError: Cannot read properties of undefined (reading 'id')
[10:25:05.175]     at getStaticProps (/vercel/path0/.next/server/pages/notes.js:360:100)
[10:25:05.175]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[10:25:05.175]     at async renderToHTML (/vercel/path0/node_modules/next/dist/server/render.js:465:20)
[10:25:05.175]     at async /vercel/path0/node_modules/next/dist/export/worker.js:269:36
[10:25:05.175]     at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:75:20)
[10:25:05.176] Error occurred prerendering page "/zh/notes". Read more: https://nextjs.org/docs/messages/prerender-error
[10:25:05.176] Error: Error serializing `.blockMap` returned from `getStaticProps` in "/notes".
[10:25:05.176] Reason: `undefined` cannot be serialized as JSON. Please use `null` or omit this value.
[10:25:05.176]     at isSerializable (/vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:30:19)
[10:25:05.176]     at /vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:37:66
[10:25:05.176]     at Array.every (<anonymous>)
[10:25:05.176]     at isSerializable (/vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:34:39)
[10:25:05.176]     at Object.isSerializableProps (/vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:57:12)
[10:25:05.176]     at renderToHTML (/vercel/path0/node_modules/next/dist/server/render.js:521:93)
[10:25:05.176]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[10:25:05.176]     at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:75:20)
[10:25:05.176] info  - Generating static pages (108/108)
[10:25:05.176] 
[10:25:05.177] > Build error occurred
[10:25:05.178] Error: Export encountered errors on following paths:
[10:25:05.179] 	/: /en
[10:25:05.179] 	/: /zh
[10:25:05.179] 	/contact
[10:25:05.180] 	/contact: /en/contact
[10:25:05.180] 	/contact: /zh/contact
[10:25:05.180] 	/newsletter: /en/newsletter
[10:25:05.180] 	/newsletter: /zh/newsletter
[10:25:05.180] 	/notes: /en/notes
[10:25:05.181]     at /vercel/path0/node_modules/next/dist/export/index.js:498:19
[10:25:05.181]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[10:25:05.181]     at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:75:20)
[10:25:05.183]     at async /vercel/path0/node_modules/next/dist/build/index.js:1024:17
[10:25:05.183]     at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:75:20)
[10:25:05.183]     at async /vercel/path0/node_modules/next/dist/build/index.js:898:13
[10:25:05.183]     at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:75:20)
[10:25:05.184]     at async Object.build [as default] (/vercel/path0/node_modules/next/dist/build/index.js:82:25)
[10:25:05.214] error Command failed with exit code 1.
[10:25:05.214] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[10:25:05.234] Error: Command "yarn run build" exited with 1
[10:25:05.556] BUILD_UTILS_SPAWN_1: Command "yarn run build" exited with 1
```

**Comment by chuxinshuo** [comment]
我也得是报这个错误..

**Comment by izuolan** [comment]
@thedavidweng 不好意思, 忘记说了, 之前有点 bug, 后来修复了, fork 最新的代码可解决.
@chuxinshuo 我 clone 了你 forked 的仓库成功跑起来了喔, 没遇到什么问题呀. 如果有报错信息就好了(可以新开个 issue).
